go.property("server", true)
go.property("server_host", msg.url("127.0.0.1"))
go.property("server_port", 9190)

------------------------------------------------------------------------------------------------------------

local utils 	= require('utils.utils')
local tiny 		= require('libs.ecs.tiny-ecs')
local wm 		= require("libs.ecs.world-manager")

local fps 		= require("libs.metrics.fps")
local mem 		= require("libs.metrics.mem")

------------------------------------------------------------------------------------------------------------

function init(self)
	local options = { host = self.server_host, port = self.server_port, noserver = not self.server }
	wm:init( options )
end

------------------------------------------------------------------------------------------------------------

function final(self)
	wm:final()
end

------------------------------------------------------------------------------------------------------------

function update(self, dt)
	
	fps.update(dt)
	mem.update()
	wm:update(dt)
end

------------------------------------------------------------------------------------------------------------

function fixed_update(self, dt)
end

------------------------------------------------------------------------------------------------------------

function on_message(self, message_id, message, sender)
end

------------------------------------------------------------------------------------------------------------

function on_input(self, action_id, action)
end

------------------------------------------------------------------------------------------------------------

function on_reload(self)
end

------------------------------------------------------------------------------------------------------------
